name: Test secrets

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
   runs-on: windows-latest  
   environment: develop

   steps:
   - name: Test simply run
     run: echo "Test simply run"

   - name: Get secrets
     run: echo ${{ secrets.TELEGRAM_BOT_TOKEN }}
